# Generated by Django 5.2.7 on 2025-10-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='car_brand',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='age',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='released_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
